##### `Semantic Search with Pinecone and embeddings using HuggingFace Model`

In [1]:
# Import Libraries

import pandas as pd
import os
from tqdm import tqdm
from dotenv import  load_dotenv
from pinecone import Pinecone , ServerlessSpec
from sentence_transformers import SentenceTransformer

c:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Load dotenv file

_ = load_dotenv(override=True)
pinecone_key = os.getenv("PINECONE_API_KEY")

In [3]:
file_path = os.path.join(os.getcwd() , "data" , "articles_new.csv")
df = pd.read_csv(file_path)

# Add another clolumn (Just an exmaple) --> to be used as metadata
df['class'] = ['class-a', 'class-b'] * 250
df

                                                 title    id    class
0                                  Mental Note Vol. 24  3054  class-a
1                            Your Brain On Coronavirus  3055  class-b
2                                       Mind Your Nose  3056  class-a
3                             The 4 Purposes of Dreams  3057  class-b
4                     Surviving a Rod Through the Head  3058  class-a
..                                                 ...   ...      ...
495  Is It Worth to Invest In Mobile E-commerce App...  3549  class-b
496          Let go of these things for a happier 2021  3550  class-a
497                Not Everyone Will like Your Writing  3551  class-b
498                             Is Technology Neutral?  3552  class-a
499                  Unveiling The Secrets of Navratri  3553  class-b

[500 rows x 3 columns]

* `Embeddings using HuggingFace Model`

In [4]:
# The Model
model_hugging_6 = SentenceTransformer(model_name_or_path="all-MiniLM-L6-v2" , device="cpu")
model_hugging_12 = SentenceTransformer(model_name_or_path="all-MiniLM-L12-v2" , device="cpu")

In [5]:
# test model for embedding 

vect_length_hugging_6 = len(model_hugging_6.encode(df["title"].iloc[0]))
print('Length of Hugging Face "all-MiniLM-L6-v2" Model is:', vect_length_hugging_6)

model_hugging_6.encode(df["title"].iloc[0])[:10]

Length of Hugging Face "all-MiniLM-L6-v2" Model is: 384

array([-0.0131355 ,  0.06555429, -0.01977038, -0.03618843, -0.07723404,
        0.10825919,  0.08496749,  0.02290436,  0.02159446,  0.00035314],
      dtype=float32)

In [6]:
# test model for embedding 
vect_length_hugging_12 = len(model_hugging_12.encode(df['title'].iloc[0]))
print('Length of Hugging Face "all-MiniLM-L12-v2" Model is:', vect_length_hugging_12)

# First 10 values
model_hugging_12.encode(df['title'].iloc[0])[:10]

Length of Hugging Face "all-MiniLM-L12-v2" Model is: 384

array([-0.00662944,  0.05047883, -0.02623439,  0.02983774,  0.01254785,
        0.00395187,  0.04635642,  0.01441403,  0.02872927,  0.05269251],
      dtype=float32)

* `Pinecone in Code`

In [8]:
# Connect to Pinecone
pc = Pinecone(api_key="pcsk_4oYw5X_QJd4vNAdAumcCFGqWdidLZaMxRgUrsai5GyLXWCRDLfsMFD5bDxrYcQ2yxjjNhY")

# Create the Index
index_name = 'quickstart'
try:
    pc.create_index(
            name=index_name,
            dimension=vect_length_hugging_6, 
            metric='cosine',              
            spec=ServerlessSpec(
                cloud='aws',
                region='us-east-1'),
            deletion_protection='enabled'
                )
except:
    pass

index = pc.Index(name=index_name)

* `Using all-MiniLM-L6-v2`

In [10]:
# Looping over the Dataset and upsert through batches
batch_size = 16
failed_ids = []

for batch_start in tqdm(range(0, len(df), batch_size)):
    try:
        # Prepare Batches
        batch_end = min(batch_start+batch_size, len(df))                            ## to handle the end of each batch
        titles_batch = df['title'][batch_start: batch_end].tolist()                 ## Slice the DF according to each batch
        ids_batch = df['id'][batch_start: batch_end].astype(str).tolist()           ## Also, Slice for the Ids according to each batch
        metadata_batch = df['class'][batch_start: batch_end].tolist()

        # Get Embeddings using HuggingFace model
        embeds_batch = model_hugging_6.encode(titles_batch).tolist()

        # Prepare data for Pinecone upsert
        to_upsert = [(id, emb, {'class': cls})
                            for id, emb, cls in zip(ids_batch, embeds_batch, metadata_batch)]
        # Insert to pinecone
        _ = index.upsert(vectors=to_upsert, namespace='HF:all-MiniLM-L6-v2')
    
    except Exception as e:
        print(f'Error Upserting: {e}')
        failed_ids.append(ids_batch)

100%|██████████| 32/32 [00:38<00:00,  1.19s/it]

* `Using all-MiniLM-L12-v2`

In [11]:
# Looping over the Dataset and upsert through batches
batch_size = 16
failed_ids = []

for batch_start in tqdm(range(0, len(df), batch_size)):
    try:
        # Prepare Batches
        batch_end = min(batch_start+batch_size, len(df))                            ## to handle the end of each batch
        titles_batch = df['title'][batch_start: batch_end].tolist()                 ## Slice the DF according to each batch
        ids_batch = df['id'][batch_start: batch_end].astype(str).tolist()           ## Also, Slice for the Ids according to each batch
        metadata_batch = df['class'][batch_start: batch_end].tolist()

        # Get Embeddings using HuggingFace model
        embeds_batch = model_hugging_12.encode(titles_batch).tolist()

        # Prepare data for Pinecone upsert
        to_upsert = [(id, emb, {'class': cls})
                             for id, emb, cls in zip(ids_batch, embeds_batch, metadata_batch)]

        # Insert to pinecone
        _ = index.upsert(vectors=to_upsert, namespace='HF:all-MiniLM-L12-v2')
    
    except Exception as e:
        print(f'Error Upserting: {e}')
        failed_ids.append(ids_batch)

100%|██████████| 32/32 [00:42<00:00,  1.32s/it]

In [12]:
# Inference (Query in real-time) (you can make more than query in one, List)
query_text = 'Neutral Technology'

# Generate Embedding for the query_text
query_embedding = model_hugging_6.encode(query_text).tolist()

# Search in pinecone
results = index.query(vector=query_embedding, 
                    top_k=5, include_metadata=True, 
                    namespace='HF:all-MiniLM-L6-v2', 
                    filter={'class': 'class-b'})

# Results
results = results['matches']
results

[{'id': '3393',
  'metadata': {'class': 'class-b'},
  'score': 0.345279366,
  'values': []},
 {'id': '3107',
  'metadata': {'class': 'class-b'},
  'score': 0.330305696,
  'values': []},
 {'id': '3311',
  'metadata': {'class': 'class-b'},
  'score': 0.225047886,
  'values': []},
 {'id': '3277',
  'metadata': {'class': 'class-b'},
  'score': 0.218963593,
  'values': []},
 {'id': '3441',
  'metadata': {'class': 'class-b'},
  'score': 0.205456868,
  'values': []}]

In [13]:
df

                                                 title    id    class
0                                  Mental Note Vol. 24  3054  class-a
1                            Your Brain On Coronavirus  3055  class-b
2                                       Mind Your Nose  3056  class-a
3                             The 4 Purposes of Dreams  3057  class-b
4                     Surviving a Rod Through the Head  3058  class-a
..                                                 ...   ...      ...
495  Is It Worth to Invest In Mobile E-commerce App...  3549  class-b
496          Let go of these things for a happier 2021  3550  class-a
497                Not Everyone Will like Your Writing  3551  class-b
498                             Is Technology Neutral?  3552  class-a
499                  Unveiling The Secrets of Navratri  3553  class-b

[500 rows x 3 columns]

In [14]:
# You can delete vectors using ids
_ = index.delete(ids=['3054', '3055'], namespace='HF:all-MiniLM-L6-v2')

In [15]:
# To update the embeddings of any id 
text_update = 'This is for updating the Id and change embeddings'
embeds_update = model_hugging_6.encode(text_update).tolist()

# Update or you can use upsert
_ = index.update(id='3191', values=embeds_update, namespace='HF:all-MiniLM-L6-v2')

In [16]:
## Fetch ids
index.fetch(ids=['3191', '3292'], namespace='HF:all-MiniLM-L6-v2')

FetchResponse(namespace='HF:all-MiniLM-L6-v2', vectors={'3292': Vector(id='3292', values=[-0.0587002821, -0.10953746, 0.0402981602, 0.0467616059, -0.0353818387, 0.0857539177, 0.0412121937, 0.0141806751, 0.00177014631, -0.0770865381, -0.0415372662, -0.0538043194, 0.0217062514, -0.0458817147, 0.0705075711, 0.0759797543, 0.0345984846, -0.100260712, 0.0140041336, -0.0515077859, 0.0896312445, -0.0768813, -0.0563248619, 0.0224374942, 0.0307733864, 0.0182192344, -0.0775668919, 0.0135552846, 0.0408200435, 0.0695489794, -0.00704766717, 0.0247531645, 0.098920472, 0.0252510887, -0.0482797, -0.00308723119, -0.00176328793, 0.0375144891, -0.0727425739, -0.00923572388, -0.00266611623, -0.0201740898, 0.0342055634, 0.0185199194, -0.0696112886, -0.0182932913, 0.00653282925, -0.0319156423, -0.043846719, 0.0264299214, 0.0211658198, -0.0810257196, -0.00519322, -0.0359051116, 0.00282149389, 0.0696480945, 0.00912587531, 0.0965562686, 0.0323681124, 0.0251859184, 0.027824318, -0.0450573228, 0.00154787372, -0.0666925088, -0.00513986684, 0.0350151844, -0.0824119598, 0.0705982447, 0.00852870848, 0.0964096934, 0.00976121891, 0.104522787, 0.0192473624, 0.00244325818, -0.0399012975, -0.00297564943, -0.079059951, -0.00602508197, -0.0654704943, -0.0445093699, 0.00842179917, -0.0567062274, -0.0261415821, -0.0294182263, 0.104251303, -0.0790026262, 0.121879421, 0.023992708, -0.112960294, -0.0363351852, -0.055408746, 0.0304215979, -0.0503272489, -0.0399137922, 0.03909624, 0.00603681, -0.0179633368, 0.0232935287, 0.062205635, 0.00123941735, 0.0108890273, 0.0160831846, -0.0506495237, 0.0486522764, 0.0623868853, -0.0719978586, -0.0609703958, 0.117075205, -0.0202629957, 0.0490649939, 0.0530100763, 0.0285122264, 0.0455426909, -0.0243591163, 0.0548172258, 0.0763198212, -0.0314713717, -0.0814456865, 0.0948026329, -0.0299240798, 0.110062324, -0.00528548378, -0.0980821326, 0.0102863703, 0.0541505665, -0.0012216731, 0.0363958515, -1.19599718e-33, 0.0193349067, 0.0533349924, -0.0364340693, -0.0703525469, 0.0203375407, 0.0225474518, -0.0898772404, 0.00420927349, 0.0199114643, -0.0193197411, -0.00369197619, -0.0930219293, 0.00235053874, 0.0345583744, -0.0411613956, -0.0621910505, 0.0525745749, 0.0968374088, 0.0760440379, -0.110973313, 0.0393549055, -0.0532916561, -0.0801016316, -0.0165191051, 0.0135283563, -0.00354937091, 0.0383636653, -0.00143114326, 0.0303050168, -0.0586695373, -0.0160149485, -0.0281232782, -0.00495287497, 0.0726561621, 0.0119499536, -0.0501173399, -0.0105754789, -0.0336575, 0.0393631049, -0.0555066057, 0.037478257, -0.0174588356, -0.0709710494, -0.000316071033, -0.0557075627, 0.0538864657, -0.055404, 0.0638668686, 0.0268228967, -0.00583356852, 0.0157728922, 0.0703118369, -0.00315351016, -0.0328302272, 0.0255723372, -0.0067017423, -0.0614216924, -0.0177189726, -0.00839949399, 0.00105023768, 0.0402465, 0.0246815551, 0.039715521, -0.0781523362, -0.053048905, 0.05934982, 0.0715432614, 0.0167601556, 0.12602888, -0.0433125645, -0.0139010428, 0.037877351, 0.0346994288, -0.0292806234, -0.0611202754, -0.0639863461, 0.0151737416, 0.00588775, -0.0713214353, 0.0423312746, 0.0192471966, -0.0893037915, -0.0501793176, 0.0807905942, 0.0336605683, -0.041201096, 0.0350641496, -0.0500828139, -0.127035633, 0.00467506703, -0.0611184463, 0.00471102819, 0.0818102956, -0.0483016111, -0.0841905773, 1.64722611e-33, 0.0355726294, -0.0133199226, 0.00990517717, 0.0131771676, 0.0528254211, 0.0696322396, 0.0287610199, 0.113600463, 0.0453186035, 0.0530719683, 0.00065148971, -0.0343863405, -0.0414611027, -0.0343571417, -0.158716947, 0.0466575138, -0.00862746313, 0.0298702922, 0.0137268575, -0.0355769321, -0.0510772057, -0.0606486164, 0.0120770084, 0.0075056348, 0.033904165, 0.0162333716, 0.0739032, 0.0196617618, 0.0268179215, -0.0264492761, 0.0646018311, 0.0327579752, -0.0722926334, -0.111420982, 0.0287410598, -0.00593526568, 0.0185702424, -0.0233095922, -0.048474811, -0.0256164577, 0.0152873816, -0.015539581, 0.0177356396, 0.00792659167, -0.0479445346, 0.0836180672, 0.0578611121, 0.07835944, -0.112669252, -0.0161174852, 0.0132108899, -0.120252021, 0.0408944376, -0.00312005077, -0.018864071, -0.00391475856, 0.0518169254, -0.0600868799, 0.00645716069, -0.00399777, -0.0416687801, -0.0582591183, -0.00163098145, -0.0916261896, 0.0786941797, 0.0472429506, 0.030000871, -0.01980168, -0.0104465215, 0.0761272833, 0.0483726151, 0.020313099, -0.0222276486, 0.0358623713, 0.0766379684, 0.0412998423, 0.0500207432, 0.058775425, -0.0936331451, -0.0428932495, 0.00816036575, 0.0463426635, 0.00827521738, -0.0686979294, 0.00552232098, 0.0174426399, 0.0145209217, 0.0638004914, -0.00824102946, 0.0475358777, -0.0617301501, 0.0668091699, 0.0814812481, 0.0526559, 0.0129713332, -1.38870933e-08, -0.0197888799, -0.00129003602, 0.00655383244, -0.0457203127, -0.00818229932, 0.0199568719, 0.0540101416, -0.00273558684, 0.0538348891, -0.0309580807, 0.0594810098, -0.0485906117, 0.0104409298, -0.0732423663, -0.0301568639, -0.0649101734, 0.00300876726, -0.00228170608, -0.026399482, -0.0140220141, 0.0172932427, 0.0671336949, -0.0883542523, 0.00881780218, 0.0245187972, 0.00875869393, 0.0836683512, 0.0563014522, -0.028490968, 0.00965341926, 0.00777443033, 0.0969791412, -0.0429923832, -0.0137033574, -0.00674482714, -0.0349331237, -0.00897108484, 0.0589101277, -0.0207340661, 0.0830450431, 0.0175773595, 0.033109758, -0.0885232612, -0.0313313492, -0.00873757154, -0.0742403865, -0.032790713, -0.0227679964, -0.0045282389, 0.0858717859, 0.0348128118, 0.0565243959, -0.0172151383, -0.0082712844, 0.0290647373, 0.0656563, 0.0320349894, -0.0119093843, -0.0258228891, 0.103598669, -0.0696156472, 0.0261792, 0.0527548864, 0.0578991026], metadata={'class': 'class-a'}, sparse_values=None), '3191': Vector(id='3191', values=[-0.0863685459, -0.0565062389, -0.0596554354, 0.0517030247, 0.0311833397, -0.106662802, -0.0539679676, 0.0847911164, -0.0917322934, 0.0162194, -0.0333555527, 0.021549467, 0.018644603, 0.0254058, 0.0330809094, 0.019693289, -0.0248837713, -0.0632453561, 0.0520105325, -0.0907492787, -0.071506463, 0.0393609256, 0.0173746254, 0.0137616647, 0.0759144947, 0.000417730334, 0.0458109342, 0.0319156647, -0.0453178138, -0.00651254691, -0.025148334, 0.036041908, 0.0315750055, 0.0250909887, 0.0282171071, 0.0397114456, 0.0358143151, -0.0176386349, -0.0437855087, 0.0391101688, -0.0282647405, -0.0238574073, -0.0289461166, 0.0124964118, -0.021586908, 0.0198517013, -0.0290683899, -0.0261580516, 0.0602782257, -0.00309366453, -0.0712299868, -0.0367986634, -0.0116504878, -0.0207066666, 0.0656233281, -0.0063583618, 0.0816948712, -0.082757175, -0.00695040403, -0.127445295, 0.00241015013, -0.0486655049, -0.0164006129, 0.0469695255, -0.0172074176, 0.0319135301, -0.067081973, 0.0956536829, 0.129908949, -0.00856891368, -0.0877829045, 0.0131555358, -0.0707394779, 0.0661213472, -0.0265935119, 0.0023845532, 0.0550996773, -0.0252878722, 0.0386499092, -0.0625240505, -0.0645106658, -0.0117966896, -0.085121, 0.0942467526, -0.0699892566, -0.00193203765, 0.0802895799, 0.0634394735, -0.04094816, -0.00498874253, 0.0824145451, 0.0269650221, 0.0537582226, -0.0100833233, -0.0683516189, 0.0684331656, 0.045573011, -0.112675026, 0.0355117954, -0.0350080207, -0.0263852626, -0.0151774473, 0.0831856802, 0.0995920151, -0.0293725338, -0.0320584103, -0.00312739797, -0.0838713124, -0.00321028032, -0.0122908447, 0.000897385646, -0.0298371557, -0.0430733114, 0.0182137676, 0.0614075512, -0.0168834068, -0.0532296374, -0.0135512548, -0.0176442899, 0.0402753912, -0.00972640328, -0.00689016143, -0.0236766394, -0.0520697273, -0.0136784064, -0.00285516796, -0.104658566, -3.42819446e-33, 0.0244664457, -0.019559117, 0.0211110171, 0.0421968699, 0.0725402161, -0.0605553836, 0.0157301556, 0.00200020592, -0.0398846418, 0.0445254184, -0.0452265851, 0.160647646, -0.0365495645, -0.00904304162, -0.0173831135, -0.00466108788, -0.0041778232, 0.0511100143, -0.0556878373, 0.0424923971, 0.0455176271, -0.00477296859, -0.0204909258, 0.01996167, 0.05656204, -0.0696204379, 0.0046840026, -0.0208076145, 0.0508495271, 0.0102430768, -0.0251113568, -0.0101294201, -0.0337686911, 0.0691280589, -0.00261203968, -0.0511765666, -0.0125506194, -0.0638817623, 0.00152733829, -0.0298703574, -0.00418333523, 0.0648822, 0.0021130282, -0.0192583762, -0.0812892765, 0.0133761279, 0.0295269061, 0.0703422725, 0.10121195, 0.0332570039, 0.0067687952, -0.0362298079, 0.0650300905, 0.0393320322, -0.034335, 0.0157470517, -0.0510280579, -0.0467578769, 0.0355987661, -0.0699454844, -0.0546513647, 0.0501343794, 0.0572677441, -0.022226179, -0.0129149398, 0.00697266636, -0.00412416831, 0.0011404719, 0.0684474185, 0.0393128097, -0.0312105, -0.0348023251, -0.0108041428, 0.0160515308, 0.0893935263, 0.0469585545, 0.0222101286, -0.0593012832, -0.0424802378, 0.0580839179, 0.0178817119, 0.0024732661, -2.26565498e-05, -0.0296810418, 0.0438429043, -0.0440300852, 0.0431350395, 0.0405556, -0.0737489536, -0.0334102288, -0.0496493243, -0.00653905887, 0.0443208925, 0.00579007668, -0.0458170213, 1.04480987e-33, 0.0604012236, -0.0187758021, 0.0432221, 0.0774100497, 0.0405299589, 0.0228022411, 0.0150761623, -0.0470027104, 0.0541607961, 0.00748286629, 1.59428582e-05, -0.0570997968, 0.0402368717, 0.00313140568, 0.0819244459, -0.0106636928, -0.0282010399, 0.0199610777, -0.047642637, 0.0351112708, -0.121141374, 0.0549466349, -0.119335167, -0.0879098, -0.00212526927, -0.00445350492, -0.0152366022, -0.0203376636, -0.0770888552, -0.0357002467, -0.0149196628, 0.0837248, -0.00900200661, 0.0144506674, -0.0224369857, 0.0532125, 0.0507572852, -0.00524029462, 0.0260868557, -0.016282849, 0.0938503221, 0.037442863, -0.0549285486, 0.0195762888, -0.0123914108, -0.0857422128, -0.0601487346, 0.121498376, -0.0390423238, -0.0220167879, -0.0303270184, 0.0323405378, 0.0733086243, -0.0478771664, 0.00417619571, -0.0292583499, 0.0845925733, 0.0526349731, -0.106519274, 0.0424603894, -0.0538750663, -0.056905251, 0.0344013795, 0.013619815, -0.136256859, -0.0713403299, -0.0140322838, 0.02244398, -0.0546446666, -0.108636521, 0.0536141656, 0.0127493348, 0.0713694543, -0.0214840788, -0.0685238615, -0.0138210552, -0.0648515299, -0.11274901, -0.0216313303, 0.0864201859, 0.0165708791, 0.0223604403, -0.00647038, 0.0629460812, -0.0565762408, 0.0549455024, -0.0210356433, 0.0190430544, 0.0431536734, -0.00123918615, -0.0898527056, -0.0463487692, -0.0287510473, 0.0918054134, 0.0419045351, -1.61400795e-08, 0.0702277198, -0.0326210558, 0.0924153551, 0.0897217318, 0.0414197668, 0.0533377677, -0.0471224971, 0.0380964652, 0.02238819, 0.0537882783, 0.0200352632, 0.0114153735, -0.0616144687, -0.0206137244, -0.0796646848, 0.0996359885, 0.0979769155, 0.0221221279, -0.0211677812, 0.0496458523, 0.0338882394, 0.0587344319, -0.0206536148, 0.033030048, 0.0514262654, -0.00715541653, 0.0333964825, -0.0245246124, 0.00465064403, -0.0659461394, 0.0513373204, -0.0780283883, 0.0185310598, 0.00328198797, 0.0189334843, -0.0403607599, 0.0336741172, 0.0608755909, -0.0302084424, -0.0150582092, -0.02210938, 0.0533332899, -0.0637112111, -0.00165885175, -0.0463080555, 0.0418747105, -0.174059987, 0.0420086943, -0.0169801805, -0.0599680468, -0.0255682394, 0.00681818184, -0.0483865812, 0.00297278818, 0.0763478279, 0.0860393643, -0.0636649877, 0.0553736463, -0.0459094867, -0.00350372819, -0.0113808699, 0.054025, 0.0593052879, -0.0195810795], metadata={'class': 'class-b'}, sparse_values=None)}, usage={'read_units': 1})